// ─── ReasoningTracePanel ──────────────────────────────────────────────────────
// Workspace panel for the Clinical Reasoning Trace.
// Expanded by default (addendum S4).
//
// Key layout change from the legacy /reasoning route (addendum S4):
//   The Hypothesis Board moves from the right sidebar into the MAIN COLUMN,
//   rendered ABOVE the timeline. The right column of the workspace is exclusively
//   the sticky action panel — no secondary sidebar here.

import type { PractitionerTrace } from '@natural-intelligence/db/crt'
import { CollapsibleSection } from './CollapsibleSection'
import { TimelineEntry }      from '../reasoning/TimelineEntry'
import { ConfidenceBar }      from '../reasoning/ConfidenceBar'

interface ReasoningTracePanelProps {
  trace: PractitionerTrace | null
}

export function ReasoningTracePanel({ trace }: ReasoningTracePanelProps) {
  if (!trace) {
    return (
      <CollapsibleSection id="reasoning" title="Reasoning Trace" defaultExpanded>
        <div style={{ padding: '24px', background: '#FFFFFF', border: '1px solid #E8E6E0', borderRadius: '8px', textAlign: 'center' }}>
          <p style={{ fontSize: '14px', color: '#8A8880', marginBottom: '4px' }}>
            No reasoning trace generated yet.
          </p>
          <p style={{ fontSize: '12px', color: '#B0AEA8' }}>
            A trace is generated automatically when the member completes their health intake.
          </p>
        </div>
      </CollapsibleSection>
    )
  }

  const hypotheses     = trace.entries.filter(e => e.entry_type === 'hypothesis')
  const timelineEntries = trace.entries.filter(e => e.entry_type !== 'client_explanation')

  return (
    <CollapsibleSection id="reasoning" title="Reasoning Trace" defaultExpanded>

      {/* Hypothesis Board — main column above timeline (S4 layout change) */}
      {hypotheses.length > 0 && (
        <div style={{ marginBottom: '24px' }}>
          <div style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#8A8880', marginBottom: '10px' }}>
            Hypothesis Board
          </div>
          <div style={{ display: 'grid', gridTemplateColumns: 'repeat(auto-fill, minmax(240px, 1fr))', gap: '10px' }}>
            {hypotheses.map((h, i) => (
              <div key={h.id} style={{ padding: '12px 14px', background: '#FFFFFF', border: '1px solid #E8E6E0', borderRadius: '8px' }}>
                <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: '6px' }}>
                  <span style={{ fontSize: '11px', fontWeight: 700, color: '#B0AEA8' }}>#{i + 1}</span>
                  {h.hypothesis_key && (
                    <span style={{ fontSize: '10px', background: '#F4F3F0', padding: '2px 6px', borderRadius: '3px', color: '#555350', fontFamily: 'monospace' }}>
                      {h.hypothesis_key}
                    </span>
                  )}
                </div>
                <p style={{ fontSize: '13px', lineHeight: '1.5', margin: '0 0 8px', color: '#1A1917' }}>
                  {h.content}
                </p>
                <ConfidenceBar value={h.confidence ?? null} />
              </div>
            ))}
          </div>
        </div>
      )}

      {/* Reasoning Timeline */}
      <div>
        <div style={{ fontSize: '11px', fontWeight: 700, textTransform: 'uppercase', letterSpacing: '0.1em', color: '#8A8880', marginBottom: '10px' }}>
          Reasoning Timeline
        </div>
        {timelineEntries.length === 0 ? (
          <p style={{ fontSize: '14px', color: '#8A8880' }}>No entries yet.</p>
        ) : (
          <div style={{ display: 'flex', flexDirection: 'column', gap: '1px', border: '1px solid #E8E6E0', borderRadius: '8px', overflow: 'hidden' }}>
            {timelineEntries.map((entry, i) => (
              <TimelineEntry key={entry.id} entry={entry} index={i} />
            ))}
          </div>
        )}
      </div>

      {/* Trace metadata */}
      <div style={{ marginTop: '16px', padding: '10px 12px', background: '#F4F3F0', borderRadius: '6px' }}>
        <p style={{ fontSize: '11px', color: '#8A8880', margin: 0, lineHeight: '1.7' }}>
          Generated by: <strong>{trace.generated_by}</strong>
          {' · '}Trace status: <strong>{trace.status}</strong>
          {' · '}Created:{' '}
          <strong>
            {new Date(trace.created_at).toLocaleDateString('en-GB', {
              day: 'numeric', month: 'short', year: 'numeric',
            })}
          </strong>
        </p>
      </div>
    </CollapsibleSection>
  )
}
